/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

int main(void)
{

	RCC_AHB1ENR_t volatile *const pClkCtrlReg = (RCC_AHB1ENR_t*)0x40023830;
	GPIOx_MODER_t volatile *const pPortDModeReg = (GPIOx_MODER_t*)0x40020c00;
	GPIOx_ODR_t volatile *const pPortRegOutReg = (GPIOx_ODR_t*)0x40020c14;

	// Enable the clock for GPIOD port
	pClkCtrlReg -> gpiod_en = 1;

	// Set bits 24th & 25th to 1 (high), which enable the general purpose output mode
	pPortDModeReg ->pinmode_12 = 1;

	while(1)
	{
		pPortRegOutReg->pin_12 = 1;

		for(uint32_t i = 0; i < 300000; i++);

		pPortRegOutReg->pin_12 = 0;

		for(uint32_t i = 0; i < 300000; i++);
	}


    /* Loop forever */
	//for(;;);
}
