/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>

int main(void)
{
	// First enable the RCC clock,the base address is 0x40023800, to the AHB1 bus: the offset is 0x30
	uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
	// Second access the port; the base address of the PortD is 0x40020C00. offset for the MODE is 0x00
	uint32_t *pPortDReg = (uint32_t*)0x40020C00;
	// Third access the GPIO output register, the offset is 0x14;
	uint32_t *pPortODReg = (uint32_t*)0x40020C14;


	// The base address of the PortA is 0x40020000 and the offset is for the MODE is 0x00
	uint32_t *pPortAReg = (uint32_t*)0x40020000;
	// Configure the input register of PortA; offset is 0x10
	uint32_t *pPortAIDReg = (uint32_t*)0x40020010;


	// Enable the clock for PortD
	*pClkCtrlReg |= (1 << 3);
	// Enable the clock for PortA
	*pClkCtrlReg |= (1 << 0);


	// Clear the bits on PortD12 before set the mode
	*pPortDReg &= ~(3 << 24);
	// Clear the bits on PortD13 before set the mode
	*pPortDReg &= ~(3 << 26);
	// Clear the bits on PortD14 before set the mode
	*pPortDReg &= ~(3 << 28);
	// Clear the bits on PortD15 before set the mode
	*pPortDReg &= ~(3 << 30);

	// Set the PortD12 MODE to General purpose output mode, bits are 01
	*pPortDReg |= (1 << 24);
	// Set the PortD13 MODE to General purpose output mode, bits are 01
	*pPortDReg |= (1 << 26);
	// Set the PortD14 MODE to General purpose output mode, bits are 01
	*pPortDReg |= (1 << 28);
	// Set the PortD14 MODE to General purpose output mode, bits are 01
	*pPortDReg |= (1 << 30);



	// Clear PortA MODE register bits, bit positions are 0 and 1 on the register
	*pPortAReg &= ~(3 << 0);
	// To SET the MODE as input, bit fields 0 and 1 have to 00 as per the doc. since, these are cleared
	// above, it doesn't required to SET them to 00.


	while(1)
	{
		uint8_t count = 0;

		if(count == 2)
		{
			count = 0;
		}
		// To read from the PortA Pin0, make the 0th but high in GPIO port data register
		uint8_t pressButton = (uint8_t)(*pPortAIDReg & 0x1);

		if(pressButton)
		{
			count ++;
		}


		if(count == 1)
		{
			//Set bit-13 high on GPIO output register.
			*pPortODReg |= (1 << 12);
			//Set bit-13 high on GPIO output register.
			*pPortODReg |= (1 << 13);
			//Set bit-14 high
			*pPortODReg |= (1 << 14);
			//Set bit-15 high
			*pPortODReg |= (1 << 15);
		}
		if(count == 2)
		{
			//Set bit-13 high on GPIO output register.
			*pPortODReg &= ~(1 << 12);
			//Set bit-13 high on GPIO output register.
			*pPortODReg &= ~(1 << 13);
			//Set bit-14 high
			*pPortODReg &= ~(1 << 14);
			//Set bit-15 high
			*pPortODReg &= ~(1 << 15);
		}

	}

    /* Loop forever */
	//for(;;);
}
